[package]
name = "StegaCean"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
# prgrs = "0.6.4"
lodepng = "3.4"
rgb = "0.8"
